### ISSUE TITLE
failed to resolve debug_unreachable

### ISSUE THREAD

**Issue by RTLS** [kmcallister/futf#11]
I am attempting to compile `html5ever` with `futf` v0.1.4 as a dependency and I encounter this error:

    ==> html5ever
      | Compiling NIF crate :html5ever_nif (native/html5ever_nif)...
      | Downloading new_debug_unreachable v1.0.2
      | Compiling new_debug_unreachable v1.0.2

    ... [Removed for brevity]...

      | Compiling futf v0.1.4
      | error[E0433]: failed to resolve. Use of undeclared type or module `core`
      | --> /var/lib/buildkite-agent/.cargo/registry/src/github.com-1ecc6299db9ec823/futf-0.1.4/src/lib.rs:136:14
      | \|
      | 136 \|         _ => debug_unreachable!(),
      | \|              ^^^^^^^^^^^^^^^^^^^^ Use of undeclared type or module `core`
      | \|
      | = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
      |  
      | error: aborting due to previous error
      |  
      | error: Could not compile `futf`.

We build using CI pretty frequently and this issue started cropping up between Feb. 10th and Feb 18th. Let me know if you have any thoughts regarding a fix. Thanks in advance.

**Comment by SimonSapin** [comment]
It looks like the error occurs inside the expansion of the `debug_unreachable` macro, which comes from https://crates.io/crates/new_debug_unreachable, which has had version 1.0.2 release on February 16th. The only new commit appears to be https://github.com/mbrubeck/rust-debug-unreachable/commit/f6ea6b23cf9c57ca65bd646304e1182a0d9e8d92, which does mention `core::`.

@mbrubeck, it looks like that commit assumes that `core` is in scope at the call site, which previous versions did not. Would it make sense for the macro expansion to include `extern crate core;`?

**Comment by SimonSapin** [comment]
Or perhaps more idiomatic would be for the macro to use `$crate::_internal::unreachable_unchecked()`, and for the crate to have a `#[doc(hidden)] pub mod _internal { pub use core::hint::unreachable_unchecked; }`

**Comment by RTLS** [comment]
Yeah that seems to be the case. Thanks for the help and for contacting @mbrubeck

**Comment by mbrubeck** [comment]
Thanks. I didn't catch that because the error doesn't occur in Rust 1.30 or newer.  I published new_debug_unreachable 1.0.3 with a fix to work with older versions.

Note that it still requires Rust 1.27 or newer. If you need to build with even older versions of Rust, the best solution right now is to pin your dependency to new_debug_unreachable 1.0.1 using Cargo.lock.
